/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package favoriteSites;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author anil
 */
public class MainForm extends javax.swing.JFrame {

    Connection conn = ConnectorSQL.getConnection();
    Statement stmt = null;
    ResultSet rs = null;
    private final String username;
    /**
     * Creates new form mainForm
     * @param username
     */
    public MainForm(String username) {
        this.username = username;
        initComponents();
    }
    
    Connection con = ConnectorSQL.getConnection();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        visitYearField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        visitIdField = new javax.swing.JTextField();
        visitedSpringButton = new javax.swing.JButton();
        mostVisitedButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bestFoodButton = new javax.swing.JButton();
        findByYearButton = new javax.swing.JButton();
        visitSharedButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        displayVisitButton = new javax.swing.JButton();
        displayImageButton = new javax.swing.JButton();
        editVisitButton = new javax.swing.JButton();
        shareVisitButton = new javax.swing.JButton();
        deleteVisitButton = new javax.swing.JButton();
        addVisitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Visit id:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, -1));

        visitYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitYearFieldActionPerformed(evt);
            }
        });
        getContentPane().add(visitYearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 83, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("visits done in the year:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));
        getContentPane().add(visitIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 83, -1));

        visitedSpringButton.setText("Visited in spring");
        visitedSpringButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitedSpringButtonActionPerformed(evt);
            }
        });
        getContentPane().add(visitedSpringButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 124, 178, -1));

        mostVisitedButton.setText("Most visited countries");
        mostVisitedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostVisitedButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mostVisitedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 165, 178, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filter results");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 109, -1));

        bestFoodButton.setText("countries with best food");
        bestFoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestFoodButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bestFoodButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 165, 178, -1));

        findByYearButton.setText("Find by year");
        findByYearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findByYearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(findByYearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 289, -1));

        visitSharedButton.setText("Visits shared with me");
        visitSharedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitSharedButtonActionPerformed(evt);
            }
        });
        getContentPane().add(visitSharedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 124, 178, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 180, 180));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("(\"all\" for the whole table)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -1, 180, 40));

        displayVisitButton.setText("Display visit");
        displayVisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayVisitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(displayVisitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 362, -1));

        displayImageButton.setText("Display image");
        displayImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayImageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(displayImageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 166, -1));

        editVisitButton.setText("Edit visit");
        editVisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVisitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editVisitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 166, -1));

        shareVisitButton.setText("Share visit");
        shareVisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareVisitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(shareVisitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 362, -1));

        deleteVisitButton.setText("Delete visit");
        deleteVisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVisitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteVisitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 178, -1));

        addVisitButton.setText("Add a visit");
        addVisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVisitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addVisitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 178, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "visit id", "username", "country name", "city name", "year visited", "season visited", "best feature", "user comment", "rating"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 964, 221));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpaperflare.com_wallpaper (3).jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1030, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostVisitedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostVisitedButtonActionPerformed
        printQuery("SELECT country_name, COUNT(*) AS visits FROM visits where username = '"+username+"' GROUP BY country_name ORDER BY visits DESC;");
    }//GEN-LAST:event_mostVisitedButtonActionPerformed

    private void visitedSpringButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitedSpringButtonActionPerformed
        printQuery("SELECT country_name FROM visits GROUP BY country_name HAVING SUM(CASE WHEN season_visited != 'spring' THEN 1 ELSE 0 END) = 0");
    }//GEN-LAST:event_visitedSpringButtonActionPerformed

    private void bestFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestFoodButtonActionPerformed
        printQuery("SELECT country_name,rating FROM visits WHERE best_feature = 'Food' ORDER BY rating DESC");
    }//GEN-LAST:event_bestFoodButtonActionPerformed

    private void findByYearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findByYearButtonActionPerformed
        String yearString = visitYearField.getText();
        printQuery("Select * from visits where year_visited = " + yearString);
    }//GEN-LAST:event_findByYearButtonActionPerformed

    private void visitYearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitYearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitYearFieldActionPerformed

    private void visitSharedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitSharedButtonActionPerformed
        printQuery("select visits.* from visits,sharedvisits where sharedvisits.friend_username = '" + username 
                + "' and visits.visit_id=sharedvisits.visit_id");
    }//GEN-LAST:event_visitSharedButtonActionPerformed

    private void deleteVisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVisitButtonActionPerformed

        String visitID = visitIdField.getText();

        if (visitID.isEmpty()) {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow != -1) {
                visitID = jTable1.getValueAt(selectedRow, 0).toString(); // İlk sütun visit_id
            } else {
                JOptionPane.showMessageDialog(this, "Please enter a visit ID or select a row to delete");
                return;
            }
        }

        PreparedStatement pstmt = null;
        Connection conn = null;

        try {
            //hem sharedvisits hem visits tablosunu düzenleyeceğimiz için autocommit false yapılmazsa
            //hata veriyor. işlemler başarılı bir şekilde gerçekleşirse commit yapılır işlemlerden biri fail
            //olursa rollback atılır.
            conn = ConnectorSQL.getConnection();
            conn.setAutoCommit(false);

            String checkSharedVisitsQuery = "SELECT COUNT(*) FROM sharedvisits WHERE visit_id = " + visitID;
            pstmt = conn.prepareStatement(checkSharedVisitsQuery);
            ResultSet rs = pstmt.executeQuery();

            //silinmek istenen row aynı zamanda sharedvisits tablosunda var ise önce o tablodan silmek gerekiyor.
            if (rs.next()) {
                String deleteSharedVisitsQuery = "DELETE FROM sharedvisits WHERE visit_id = ?";
                pstmt = conn.prepareStatement(deleteSharedVisitsQuery);
                pstmt.setInt(1, Integer.parseInt(visitID));
                pstmt.executeUpdate();
            }

            // Daha sonra visits tablosundaki ilgili satırı sil
            String deleteVisitsQuery = "DELETE FROM visits WHERE visit_id = ?";
            pstmt = conn.prepareStatement(deleteVisitsQuery);
            pstmt.setInt(1, Integer.parseInt(visitID));
            int affectedRows = pstmt.executeUpdate();

            // silinen satır varsa commit yap
            if (affectedRows > 0) {
                conn.commit();
                JOptionPane.showMessageDialog(this, "Visit deleted successfully!");
                printQuery("SELECT * from visits");
            } else {
                conn.rollback(); // Herhangi bir satır silinmediyse rollback yap
                JOptionPane.showMessageDialog(this, "No visit found with the given ID.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            if (conn != null) {
                try {
                    conn.rollback(); // Hata durumunda rollback yap
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            JOptionPane.showMessageDialog(this, "Error deleting visit: " + e.getMessage());
        }

    }//GEN-LAST:event_deleteVisitButtonActionPerformed

    private void addVisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVisitButtonActionPerformed
        new AddVisitForm(username).setVisible(true);
    }//GEN-LAST:event_addVisitButtonActionPerformed

    private void editVisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVisitButtonActionPerformed
        
        String visitID = visitIdField.getText();

        if (visitID.isEmpty()) {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow != -1) {
                visitID = jTable1.getValueAt(selectedRow, 0).toString(); // İlk sütun visit_id
            } else {
                JOptionPane.showMessageDialog(this, "Please enter a visit ID or select a row to delete");
                return;
            }
        }
        
        new EditVisitForm(username, Integer.parseInt(visitID)).setVisible(true);
        
    }//GEN-LAST:event_editVisitButtonActionPerformed

    private void displayImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayImageButtonActionPerformed
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Location"+visitIdField.getText()+".jpg")));
    }//GEN-LAST:event_displayImageButtonActionPerformed

    private void displayVisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayVisitButtonActionPerformed

        String visitID = visitIdField.getText();

        if (visitID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a visit ID");
            return;
        }

        String query = null;

        if (visitID.equals("all")) {
            query = "SELECT * FROM visits";
        } else {
            query = "SELECT * FROM visits WHERE visit_id = "+ visitID;
        }
        
        visitIdField.setText("");

        printQuery(query);

    }//GEN-LAST:event_displayVisitButtonActionPerformed

    private void shareVisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareVisitButtonActionPerformed
        new ShareVisitForm(username).setVisible(true);
    }//GEN-LAST:event_shareVisitButtonActionPerformed

private void printQuery(String query){
    
        try {
            
            conn = ConnectorSQL.getConnection();
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = stmt.executeQuery(query);

            TableCreator model = new TableCreator(rs, stmt);
            jTable1.setModel(model);
        
        } catch (SQLException e) {
        e.printStackTrace();
        }
        
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm("aragorn").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVisitButton;
    private javax.swing.JButton bestFoodButton;
    private javax.swing.JButton deleteVisitButton;
    private javax.swing.JButton displayImageButton;
    private javax.swing.JButton displayVisitButton;
    private javax.swing.JButton editVisitButton;
    private javax.swing.JButton findByYearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton mostVisitedButton;
    private javax.swing.JButton shareVisitButton;
    private javax.swing.JTextField visitIdField;
    private javax.swing.JButton visitSharedButton;
    private javax.swing.JTextField visitYearField;
    private javax.swing.JButton visitedSpringButton;
    // End of variables declaration//GEN-END:variables
}
