/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package favoriteSites;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author anil
 */
public class ShareVisitForm extends javax.swing.JFrame {
    
    Connection conn = ConnectorSQL.getConnection();
    String username;
    
    /**
     * Creates new form ShareVisit
     */
    public ShareVisitForm(String username) {
        this.username=username;
        initComponents();
        setDefaultCloseOperation(MainForm.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameField = new javax.swing.JTextField();
        visitIdField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        shareButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 131, -1));
        getContentPane().add(visitIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 131, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Visit id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username to send");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        shareButton.setText("Share");
        shareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareButtonActionPerformed(evt);
            }
        });
        getContentPane().add(shareButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 280, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimalist-landscape-37tm47643y89ta2i.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareButtonActionPerformed
       
            String friendUsername = usernameField.getText();
            int visitId = Integer.parseInt(visitIdField.getText());

            try {
                PreparedStatement pstmt = conn.prepareStatement("INSERT INTO sharedvisits (visit_id, sharer_username, friend_username) VALUES (?, ?, ?)");
                pstmt.setInt(1, visitId);
                pstmt.setString(2, username);
                pstmt.setString(3, friendUsername);
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Record added.");
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        
    }//GEN-LAST:event_shareButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShareVisitForm("Anil").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton shareButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField visitIdField;
    // End of variables declaration//GEN-END:variables
}
